version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: gestaopedidos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - \"5432:5432\"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=gestaopedidos;Username=postgres;Password=admin@123
    ports:
      - \"5158:5158\"
    depends_on:
      - db

volumes:
  pgdata: